/* eslint-disable @next/next/no-html-link-for-pages */
import { AuthProvider } from "@repo/auth/client/provider";
import { SignInButton } from "@repo/auth/client/sign-in-button";
import { SignOutButton } from "@repo/auth/client/sign-out-button";
import { SignedIn } from "@repo/auth/client/signed-in";
import { SignedOut } from "@repo/auth/client/signed-out";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserInfo } from "./user-info";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
            <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start">
              <h1>DEMO 1</h1>
              <SignedOut>
                <SignInButton className="bg-green-500 text-black p-2">
                  Please sign in
                </SignInButton>
              </SignedOut>
              <SignedIn>
                <SignOutButton className="bg-red-500 text-white p-2">
                  Sign out
                </SignOutButton>
              </SignedIn>
              <a href="/" className="px-4 py-2 bg-green-400 text-black">
                Go to home
              </a>
              <a href="/demo2" className="px-4 py-2 bg-green-400 text-black">
                Go to demo2
              </a>
              <UserInfo />

              <div className="p-8 bg-rose-400 rounded">{children}</div>
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
